services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default

  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - default

networks:
  default: