services:
  pg_db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    environment:
      - CONFIG_PATH
    depends_on:
      pg_db:
        condition: service_healthy
    ports:
      - '9000:9000'
      - '9001:9001'
    hostname:
      localhost

#    ports:
#      - "5432:5432"
#    volumes:
#       - pg-data:/var/lib/postgresql/data
#volumes:
#  pg-data:
