global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'metrics'
    metrics_path: /
    static_configs:
      - targets: ['host.docker.internal:9003']
