stages:
  - lint

lint:
  stage: lint
  image: golang:1.22
  script:
    - cd Homework-2
    - go mod tidy
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - golangci-lint run ./... --config ../..golangci.yml
