// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pvz.proto

package api_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelPVZ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contacts string `protobuf:"bytes,4,opt,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *ModelPVZ) Reset() {
	*x = ModelPVZ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelPVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPVZ) ProtoMessage() {}

func (x *ModelPVZ) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPVZ.ProtoReflect.Descriptor instead.
func (*ModelPVZ) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{0}
}

func (x *ModelPVZ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelPVZ) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelPVZ) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ModelPVZ) GetContacts() string {
	if x != nil {
		return x.Contacts
	}
	return ""
}

type CreatePVZReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Contacts string `protobuf:"bytes,3,opt,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *CreatePVZReq) Reset() {
	*x = CreatePVZReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePVZReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePVZReq) ProtoMessage() {}

func (x *CreatePVZReq) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePVZReq.ProtoReflect.Descriptor instead.
func (*CreatePVZReq) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePVZReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePVZReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreatePVZReq) GetContacts() string {
	if x != nil {
		return x.Contacts
	}
	return ""
}

type CreatePVZResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePVZResp) Reset() {
	*x = CreatePVZResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePVZResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePVZResp) ProtoMessage() {}

func (x *CreatePVZResp) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePVZResp.ProtoReflect.Descriptor instead.
func (*CreatePVZResp) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePVZResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPVZsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPVZsReq) Reset() {
	*x = ListPVZsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPVZsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZsReq) ProtoMessage() {}

func (x *ListPVZsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZsReq.ProtoReflect.Descriptor instead.
func (*ListPVZsReq) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{3}
}

type ListPVZsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pvzs []*ModelPVZ `protobuf:"bytes,1,rep,name=pvzs,proto3" json:"pvzs,omitempty"`
}

func (x *ListPVZsResp) Reset() {
	*x = ListPVZsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPVZsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPVZsResp) ProtoMessage() {}

func (x *ListPVZsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPVZsResp.ProtoReflect.Descriptor instead.
func (*ListPVZsResp) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{4}
}

func (x *ListPVZsResp) GetPvzs() []*ModelPVZ {
	if x != nil {
		return x.Pvzs
	}
	return nil
}

type GetPVZByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPVZByIDReq) Reset() {
	*x = GetPVZByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPVZByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPVZByIDReq) ProtoMessage() {}

func (x *GetPVZByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPVZByIDReq.ProtoReflect.Descriptor instead.
func (*GetPVZByIDReq) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{5}
}

func (x *GetPVZByIDReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPVZByIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contacts string `protobuf:"bytes,4,opt,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *GetPVZByIDResp) Reset() {
	*x = GetPVZByIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPVZByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPVZByIDResp) ProtoMessage() {}

func (x *GetPVZByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPVZByIDResp.ProtoReflect.Descriptor instead.
func (*GetPVZByIDResp) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{6}
}

func (x *GetPVZByIDResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPVZByIDResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPVZByIDResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetPVZByIDResp) GetContacts() string {
	if x != nil {
		return x.Contacts
	}
	return ""
}

type UpdatePVZReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contacts string `protobuf:"bytes,4,opt,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *UpdatePVZReq) Reset() {
	*x = UpdatePVZReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePVZReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePVZReq) ProtoMessage() {}

func (x *UpdatePVZReq) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePVZReq.ProtoReflect.Descriptor instead.
func (*UpdatePVZReq) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePVZReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePVZReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePVZReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdatePVZReq) GetContacts() string {
	if x != nil {
		return x.Contacts
	}
	return ""
}

type UpdatePVZResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *UpdatePVZResp) Reset() {
	*x = UpdatePVZResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePVZResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePVZResp) ProtoMessage() {}

func (x *UpdatePVZResp) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePVZResp.ProtoReflect.Descriptor instead.
func (*UpdatePVZResp) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePVZResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DeletePVZReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePVZReq) Reset() {
	*x = DeletePVZReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePVZReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePVZReq) ProtoMessage() {}

func (x *DeletePVZReq) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePVZReq.ProtoReflect.Descriptor instead.
func (*DeletePVZReq) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePVZReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePVZResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *DeletePVZResp) Reset() {
	*x = DeletePVZResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pvz_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePVZResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePVZResp) ProtoMessage() {}

func (x *DeletePVZResp) ProtoReflect() protoreflect.Message {
	mi := &file_pvz_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePVZResp.ProtoReflect.Descriptor instead.
func (*DeletePVZResp) Descriptor() ([]byte, []int) {
	return file_pvz_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePVZResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_pvz_proto protoreflect.FileDescriptor

var file_pvz_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x76, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x50, 0x56, 0x5a, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x22, 0x58,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x56, 0x5a, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x56, 0x5a, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x56, 0x5a, 0x73, 0x52, 0x65, 0x71, 0x22, 0x39, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x56, 0x5a, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x76, 0x7a, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x56, 0x5a, 0x52, 0x04, 0x70,
	0x76, 0x7a, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x56, 0x5a, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x6a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x56, 0x5a, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73,
	0x22, 0x68, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x56, 0x5a, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x56, 0x5a, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x56, 0x5a, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x56, 0x5a, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e,
	0x64, 0x65, 0x76, 0x2f, 0x7a, 0x6c, 0x61, 0x74, 0x6f, 0x69, 0x76, 0x61, 0x6e, 0x34, 0x2f, 0x68,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pvz_proto_rawDescOnce sync.Once
	file_pvz_proto_rawDescData = file_pvz_proto_rawDesc
)

func file_pvz_proto_rawDescGZIP() []byte {
	file_pvz_proto_rawDescOnce.Do(func() {
		file_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(file_pvz_proto_rawDescData)
	})
	return file_pvz_proto_rawDescData
}

var file_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pvz_proto_goTypes = []interface{}{
	(*ModelPVZ)(nil),       // 0: grpc_server.modelPVZ
	(*CreatePVZReq)(nil),   // 1: grpc_server.CreatePVZReq
	(*CreatePVZResp)(nil),  // 2: grpc_server.CreatePVZResp
	(*ListPVZsReq)(nil),    // 3: grpc_server.ListPVZsReq
	(*ListPVZsResp)(nil),   // 4: grpc_server.ListPVZsResp
	(*GetPVZByIDReq)(nil),  // 5: grpc_server.GetPVZByIDReq
	(*GetPVZByIDResp)(nil), // 6: grpc_server.GetPVZByIDResp
	(*UpdatePVZReq)(nil),   // 7: grpc_server.UpdatePVZReq
	(*UpdatePVZResp)(nil),  // 8: grpc_server.UpdatePVZResp
	(*DeletePVZReq)(nil),   // 9: grpc_server.DeletePVZReq
	(*DeletePVZResp)(nil),  // 10: grpc_server.DeletePVZResp
}
var file_pvz_proto_depIdxs = []int32{
	0, // 0: grpc_server.ListPVZsResp.pvzs:type_name -> grpc_server.modelPVZ
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pvz_proto_init() }
func file_pvz_proto_init() {
	if File_pvz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pvz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelPVZ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePVZReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePVZResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPVZsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPVZsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPVZByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPVZByIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePVZReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePVZResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePVZReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pvz_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePVZResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pvz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pvz_proto_goTypes,
		DependencyIndexes: file_pvz_proto_depIdxs,
		MessageInfos:      file_pvz_proto_msgTypes,
	}.Build()
	File_pvz_proto = out.File
	file_pvz_proto_rawDesc = nil
	file_pvz_proto_goTypes = nil
	file_pvz_proto_depIdxs = nil
}
