server:
  http_port: 9000
  https_port: 9001
  pvz_auth_login: ivan
  pvz_auth_password: the_best_pass

postgres:
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: postgres