server:
  http_port: 9000
  https_port: 9001
  pvz_auth_login: ivan
  pvz_auth_password: pvz_best_pass
  order_auth_login: ivan
  order_auth_password: order_best_pass
  brokers: ['localhost:9092']
  topic: crud

postgres:
  host: localhost
  port: 5433
  dbname: postgres
  user: postgres
  password: postgres