services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: ./config
    env_file: config/config.yaml
    depends_on:
      - postgres
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - default
